# Generated by Django 3.0.8 on 2020-07-31 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injuryTrack', '0004_auto_20200731_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='addedOn',
            field=models.DateTimeField(default=datetime.date(2020, 7, 31)),
        ),
        migrations.AlterField(
            model_name='injury',
            name='addedOn',
            field=models.DateTimeField(default=datetime.date(2020, 7, 31)),
        ),
    ]
