# Generated by Django 3.0.8 on 2020-07-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injuryTrack', '0005_auto_20200731_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='injury',
            name='removedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
