# Generated by Django 3.0.8 on 2020-07-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injuryTrack', '0008_auto_20200731_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='duration',
        ),
        migrations.AddField(
            model_name='exercise',
            name='durationMinutes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='durationSeconds',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
