# Generated by Django 3.0.8 on 2020-07-31 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injuryTrack', '0011_auto_20200731_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='addedOn',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='injury',
            name='addedOn',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
