# Generated by Django 3.0.8 on 2020-07-31 18:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('injuryTrack', '0013_auto_20200731_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='atc',
            name='fullname',
            field=models.CharField(default='emma johnson', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athlete',
            name='fullname',
            field=models.CharField(default='bob bobert', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='addedOn',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 18, 45, 6, 516431, tzinfo=utc)),
        ),
    ]
