# Generated by Django 3.0.8 on 2020-07-31 19:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('injuryTrack', '0014_auto_20200731_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='addedOn',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 19, 58, 32, 328259, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='injury',
            name='addedOn',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 19, 58, 32, 327510, tzinfo=utc)),
        ),
    ]
