# Generated by Django 3.0.8 on 2020-07-31 20:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('injuryTrack', '0015_auto_20200731_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='addedOn',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 20, 7, 13, 603070, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='injury',
            name='addedOn',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 20, 7, 13, 602099, tzinfo=utc)),
        ),
    ]
