# Generated by Django 3.0.8 on 2020-07-31 20:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('injuryTrack', '0016_auto_20200731_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='addedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 31, 20, 36, 39, 879581, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='addedOn',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 20, 36, 39, 880972, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='injury',
            name='addedOn',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 20, 36, 39, 880261, tzinfo=utc)),
        ),
    ]
